import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { useQuery } from 'react-query';
import { getFeatures } from '../utils/api';
import Loading from '../components/Loading';
import Dashboard from '../components/dashboard/Dashboard';
import Flex from "@utils/Flex";
import Link from "next/link";

export default function Home() {

  const {isLoading, error, data } = useQuery('getFeatures', () => getFeatures());

  if(isLoading || error) return <Loading/>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Piano roadmap notifier</h2>
        <Flex gap={3}>
            <h3>Upcoming features</h3>
            <h3>Other roadmap features</h3>
            <Link href="Watching" as="watching">
              <h3>My watched items</h3>
            </Link>
        </Flex>
        <Dashboard data={data.features}/>
    </div>
  )
}